version: '3.3'
services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        command: /bin/sh -c "while sleep 1000; do :; done"
        env_file:
            - .env
        volumes:
            - ..:/usr/src/app:cached
