version: '3.3'
services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        command: /bin/sh -c "while sleep 1000; do :; done"
        env_file:
            - .env
        volumes:
            - ..:/usr/src/app:cached
        networks:
            - feed2tweet-network

    redis:
        container_name: feed2tweet-redis
        image: redis:6
        volumes:
            - ./redis:/data
        networks:
            - feed2tweet-network

networks:
    feed2tweet-network:
        name: feed2tweet-network
