version: '3.3'
services:
    app:
        command: /bin/sh -c "while sleep 1000; do :; done"
        volumes:
            - ./app:/usr/src/app:cached
            - ./.editorconfig:/usr/src/app/.editorconfig
