name: feed2tweet

on:
  schedule:
    - cron: '3-59/10 * * * *'
  workflow_dispatch:

env:
  STATE_FILE: './tweeted'
  CACHE_KEY: 'tweeted-'

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: actions/cache用keyの生成
        run: echo "CACHE_TIMESTAMP=$(date +%s)" >> "$GITHUB_ENV"

      - uses: actions/cache@v3
        id: tweeted
        with:
          path: ${{ env.STATE_FILE }}
          key: ${{ env.CACHE_KEY }}${{ env.CACHE_TIMESTAMP }} # 毎回、最新のキャッシュを保存するためにIDを指定する
          restore-keys: ${{ env.CACHE_KEY }} # 復元時は最新のキャッシュを指定する

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Exce App
        env:
          FEED_URL: ${{ vars.FEED_URL }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python main.py

      - name: Cleanup cache
        run: |
          gh extension install actions/gh-actions-cache

          # キャッシュがない場合にエラーとなって停止するのを防ぐ
          set +e

          # 作成から1日以上経っているキャッシュを削除
          for KEY in $(gh actions-cache list -R "${REPO}" -B "${BRANCH}" --key ${{ env.CACHE_KEY }} --order asc --sort created-at | grep -P 'days? ago' | cut -f 1)
          do
              echo "Deleting ${KEY}"
              gh actions-cache delete "${KEY}" -R "${REPO}" -B "${BRANCH}" --confirm
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref }}
