name: feed2tweet

on:
  schedule:
    - cron: '3-59/10 * * * *'
  workflow_dispatch:

env:
  STATE_FILE: './tweeted'
  CACHE_KEY: 'tweeted-'

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: actions/cache用keyの生成
        run: echo "CACHE_TIMESTAMP=$(date +%s)" >> "$GITHUB_ENV"

      - uses: actions/cache@v4
        id: tweeted
        with:
          path: ${{ env.STATE_FILE }}
          key: ${{ env.CACHE_KEY }}${{ env.CACHE_TIMESTAMP }} # 毎回、最新のキャッシュを保存するためにIDを指定する
          restore-keys: ${{ env.CACHE_KEY }} # 復元時は最新のキャッシュを指定する

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Exce App
        env:
          FEED_URL: ${{ vars.FEED_URL }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          MISSKEY_ADDRESS: ${{ vars.MISSKEY_ADDRESS }}
          MISSKEY_TOKEN: ${{ secrets.MISSKEY_TOKEN }}
          UNTWEETED_MAX_NUM: ${{ vars.UNTWEETED_MAX_NUM || '3' }}
          TWEET_INTERVAL: ${{ vars.TWEET_INTERVAL || '5' }}
        run: python main.py

      - name: Cleanup cache
        run: |
          # 新しいものから5個を残してキャッシュ削除
          gh cache list --key tweeted- --order asc --sort created_at --json id | \
            jq -r '.[0:-5][].id' | \
            xargs -r -I ID gh cache delete ID
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref }}
